version: "3.8"

# Add external network reference
networks:
  scripts_default:
    external: true

# Override ALL services to use both default and scripts_default networks
services:
  koku-base:
    networks:
      - default
      - scripts_default

  koku-server:
    networks:
      - default
      - scripts_default

  masu-server:
    networks:
      - default
      - scripts_default

  koku-worker:
    networks:
      - default
      - scripts_default

  koku-listener:
    environment:
      - RETAIN_NUM_MONTHS=1200
    networks:
      - default
      - scripts_default

  redis:
    image: quay.io/insights-onprem/redis-ephemeral:6

  unleash:
    image: quay.io/ydayagi/unleashorg/unleash-server:latest
    networks:
      - default
      - scripts_default

  minio:
    image: quay.io/minio/minio:RELEASE.2025-01-20T14-49-07Z

  create-parquet-bucket:
    image: quay.io/minio/mc:latest
  # Add any other services you have...
